version: '2'
services:
    jhipsterjwtapplication-app:
        image: jhipsterjwtapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterjwtapplication-mysql:3306/jhipsterjwtapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterjwtapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsterjwtapplication-mysql
